#pragma once




namespace SDK
{
//---------------------------------------------------------------------------------------------------------------------
// CLASSES
//---------------------------------------------------------------------------------------------------------------------

// 0x4A4 (0x9F4 - 0x550)
// WidgetBlueprintGeneratedClass UI_Lobby_CosmeticCustomization.UI_Lobby_CosmeticCustomization_C
class UUI_Lobby_CosmeticCustomization_C : public URHWidget
{
public:
	struct Engine_PointerToUberGraphFrame        UberGraphFrame;                                    // 0x550(0x8)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                      AnimOnShown;                                       // 0x558(0x8)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                      AnimStateToggle;                                   // 0x560(0x8)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UUI_Button_Menu_C*                     AllFilter;                                         // 0x568(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                               BackButton;                                        // 0x570(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                          CharacterSlots;                                    // 0x578(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_Button_Menu_Gold_C*                EquipButton;                                       // 0x580(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_Button_Menu_C*                     EquippedFilter;                                    // 0x588(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                        FilterBox;                                         // 0x590(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetSwitcher*                       GamepadTopFaceSwitcher;                            // 0x598(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                Image_72;                                          // 0x5A0(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                          OptionGroup;                                       // 0x5A8(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                          OptionsList;                                       // 0x5B0(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UScrollBox*                            OptionsScrollBox;                                  // 0x5B8(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class URetainerBox*                          RetainerBox_0;                                     // 0x5C0(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_Shared_Preview_Rotator_C*          Rotator;                                           // 0x5C8(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                          SelectionGroup;                                    // 0x5D0(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                            SelectionPanelTitle;                               // 0x5D8(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UScrollBox*                            SelectionScroll;                                   // 0x5E0(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_Shared_CustomizationSelector_C*    UI_Shared_CustomizationSelector;                   // 0x5E8(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_Shared_CustomizationSelector_C*    UI_Shared_CustomizationSelector_145;               // 0x5F0(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_Shared_CustomizationSelector_C*    UI_Shared_CustomizationSelector_408;               // 0x5F8(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_Shared_CustomizationSelector_C*    UI_Shared_CustomizationSelector_511;               // 0x600(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetSwitcher*                       ViewSwitcher;                                      // 0x608(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                          WeaponSlots;                                       // 0x610(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class ACameraActor*                          CachedCamera;                                      // 0x618(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class ACameraActor*                          CachedCamera_EaseIn;                               // 0x620(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct GameplayTags_GameplayTag              CachedEquipSlot;                                   // 0x628(0x8)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	TMap<struct GameplayTags_GameplayTag, class UUI_Shared_CustomizationSelector_C*> CachedWeaponMap;                                   // 0x630(0x50)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	struct GameplayTags_GameplayTagContainer     DefaultWeaponSlotTags;                             // 0x680(0x20)(Edit, BlueprintVisible, DisableEditOnInstance)
	int32                                        SelectedFilterIndex;                               // 0x6A0(0x4)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                        Pad_43DF[0x4];                                     // Fixing Size After Last Property  
	TMap<int32, class UUI_Button_Menu_C*>        NavTabMap;                                         // 0x6A8(0x50)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	class UValPreviewManager*                    PreviewManager;                                    // 0x6F8(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	TMap<int32, class UUI_Shared_CustomizationSelector_C*> CachedSelectorMap;                                 // 0x700(0x50)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	bool                                         CachedSelectingState;                              // 0x750(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                        Pad_43E2[0x7];                                     // Fixing Size After Last Property  
	TArray<class UUI_Shared_CustomizationOption_C*> CachedOptionWidgets;                               // 0x758(0x10)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	TMap<struct GameplayTags_GameplayTag, struct GameplayTags_GameplayTag> CachedEquippedTags;                                // 0x768(0x50)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                         CachedSelectingWeapon;                             // 0x7B8(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                        Pad_43E5[0x7];                                     // Fixing Size After Last Property  
	class AValInventoryManager*                  CachedInventoryManager;                            // 0x7C0(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UValLoadoutDefinition*                 AppearanceLoadoutDefinition;                       // 0x7C8(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class FName                                  DefaultCameraTag;                                  // 0x7D0(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TMap<struct GameplayTags_GameplayTag, class FName> GameplayTagToCameraName;                           // 0x7D8(0x50)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FName                                  ActiveCameraTag;                                   // 0x828(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                         CachedSelectingJetpack;                            // 0x830(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                        Pad_43E6[0x7];                                     // Fixing Size After Last Property  
	struct Valhalla_InventoryItem                CachedEquippedItem;                                // 0x838(0xC8)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct Valhalla_InventoryItem                CachedSelectedItem;                                // 0x900(0xC8)(Edit, BlueprintVisible, DisableEditOnInstance)
	class UUI_Shared_CustomizationOption_C*      CachedSelectedOptionWidget;                        // 0x9C8(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                        LoadoutSlotsFocusGroup;                            // 0x9D0(0x4)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                        OptionsFocusGroup;                                 // 0x9D4(0x4)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUI_Shared_CustomizationSelector_C*    CachedSelectedSlotWidget;                          // 0x9D8(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	FMulticastInlineDelegateProperty_            OnSelectingViewState;                              // 0x9E0(0x10)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	int32                                        CachedFilterValue;                                 // 0x9F0(0x4)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

	static class UClass* StaticClass();
	static class UUI_Lobby_CosmeticCustomization_C* GetDefaultObj();

	void HandleBackPressed(bool CallFunc_NavigateBack_ReturnValue);
	void On_Toggle_Weapons_Filter(int32 CallFunc_GetChildrenCount_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_Greater_IntInt_ReturnValue);
	void SetupSelectorContextActions(TArray<class FName>& K2Node_MakeArray_Array, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate);
	void SetupDefaultContextActions(FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, TArray<class FName>& K2Node_MakeArray_Array);
	void SetupOptionsContextActions(FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, TArray<class FName>& K2Node_MakeArray_Array);
	void Update_Selection_Prompts(bool Condition);
	void OnShown();
	void OnHide(class AValPlayerController* CallFunc_GetPlayer_ReturnValue, class AValInventoryManager* CallFunc_GetInventoryManager_ReturnValue, class AValPlayerController_City* K2Node_DynamicCast_AsVal_Player_Controller_City, bool K2Node_DynamicCast_bSuccess, class UValPreviewManager* CallFunc_GetPreviewManager_ReturnValue, bool CallFunc_IsValid_ReturnValue);
	void VerifyGamepadAndScroll(class UScrollBox* ScrollBox, class UWidget* Widget, enum class EDescendantScrollDestination ScrollDestination, enum class ERH_INPUT_STATE CallFunc_GetCurrentInputState_ReturnValue, bool CallFunc_EqualEqual_ByteByte_ReturnValue);
	void HandleInputStateChanged(enum class ERH_INPUT_STATE InputState, bool Temp_bool_Variable, bool CallFunc_EqualEqual_ByteByte_ReturnValue, enum class ESlateVisibility Temp_byte_Variable, enum class ESlateVisibility Temp_byte_Variable_1, enum class ESlateVisibility K2Node_Select_Default);
	void OnSlotHovered(class UUI_Shared_CustomizationSelector_C* Widget);
	void OnGamepadConfirmOption(class UUI_Shared_CustomizationOption_C* Widget);
	bool NavigateBack(bool CallFunc_RemoveTopViewRoute_ReturnValue, class UWidget* CallFunc_GetActiveWidget_ReturnValue, bool CallFunc_EqualEqual_ObjectObject_ReturnValue, bool CallFunc_NavigateBack_ReturnValue);
	void InitSlotWidgetNavigation(TArray<class URHWidget*>& CallFunc_GetSlotNavigationWidgets_NewParam, class URHWidget* CallFunc_Array_Get_Item);
	void GetSlotNavigationWidgets(TArray<class URHWidget*>* NewParam, const TArray<class URHWidget*>& NewLocalVar, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Array_Index_Variable_1, int32 Temp_int_Loop_Counter_Variable_1, TArray<class UWidget*>& CallFunc_GetAllChildren_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_1, class UWidget* CallFunc_Array_Get_Item, class UUI_Shared_CustomizationSelector_C* K2Node_DynamicCast_AsUI_Shared_Customization_Selector, bool K2Node_DynamicCast_bSuccess, int32 CallFunc_Array_Length_ReturnValue, int32 CallFunc_Array_Add_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, TArray<class UWidget*>& CallFunc_GetAllChildren_ReturnValue_1, int32 CallFunc_Array_Length_ReturnValue_1, class UWidget* CallFunc_Array_Get_Item_1, bool CallFunc_Less_IntInt_ReturnValue_1, class UUI_Shared_CustomizationSelector_C* K2Node_DynamicCast_AsUI_Shared_Customization_Selector_1, bool K2Node_DynamicCast_bSuccess_1, int32 CallFunc_Array_Add_ReturnValue_1);
	void EquipSelectedItem(class AValInventoryManager* CallFunc_GetInventoryManager_ReturnValue);
	void CompareItems(struct Valhalla_InventoryItem& Item_A, struct Valhalla_InventoryItem& Item_B, bool* ItemsDiffer, bool CallFunc_NotEqual_IntInt_ReturnValue, bool CallFunc_NotEqual_GuidGuid_ReturnValue, bool CallFunc_BooleanOR_ReturnValue);
	void UpdateEquipButtonState(bool CallFunc_CompareItems_ItemsDiffer);
	void RestorePreviouslyEquippedJetpack(class AValInventoryManager* CallFunc_GetInventoryManager_ReturnValue, const struct Valhalla_InventoryItem& CallFunc_GetEquippedCosmeticItemsAt_InventoryItem, bool CallFunc_GetEquippedCosmeticItemsAt_ReturnValue, bool CallFunc_NotEqual_IntInt_ReturnValue, class AValInventoryManager* CallFunc_GetInventoryManager_ReturnValue_1, bool CallFunc_IsSelectingJetpack_Value);
	void GetCameraTag(const struct GameplayTags_GameplayTag& GameplayTag, class FName* CameraTag, bool CallFunc_IsGameplayTagValid_ReturnValue, class FName CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue);
	void IsSelectingJetpack(bool* Value, bool CallFunc_MatchesTag_ReturnValue, bool CallFunc_BooleanAND_ReturnValue);
	void GetAppearanceAudioVisual(class UValDeviceAudioVisual** AudioVisual, class UValItemAsset* CallFunc_GetAppearanceAsset_ItemAsset, bool CallFunc_IsValid_ReturnValue, class UClass* K2Node_ClassDynamicCast_AsVal_Device, bool K2Node_ClassDynamicCast_bSuccess);
	void OnInitialized(FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate);
	void GetInventoryManager(class AValInventoryManager** InventoryManager, class AValInventoryManager* CallFunc_GetInventoryManager_ReturnValue, bool CallFunc_IsValid_ReturnValue, bool CallFunc_IsValid_ReturnValue_1);
	void GetAppearanceAsset(class UValItemAsset** ItemAsset, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, class AValGameState* CallFunc_GetGameState_ReturnValue, class AValGameState_Lobby* K2Node_DynamicCast_AsVal_Game_State_Lobby, bool K2Node_DynamicCast_bSuccess, TArray<struct Valhalla_WeaponCosmeticConfig>& CallFunc_GetWeaponCosmeticConfigs_WeaponCosmeticConfigs, int32 CallFunc_Array_Length_ReturnValue, const struct Valhalla_WeaponCosmeticConfig& CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_EqualEqual_GameplayTag_ReturnValue, class UObject* CallFunc_Conv_SoftObjectReferenceToObject_ReturnValue, class UValItemAsset* K2Node_DynamicCast_AsVal_Item_Asset, bool K2Node_DynamicCast_bSuccess_1);
	void GetPreviewManager(class UValPreviewManager** PreviewManager, bool* Valid, bool CallFunc_IsValid_ReturnValue, class AValPlayerController* CallFunc_GetPlayer_ReturnValue, class AValPlayerController_City* K2Node_DynamicCast_AsVal_Player_Controller_City, bool K2Node_DynamicCast_bSuccess, class UValPreviewManager* CallFunc_GetPreviewManager_ReturnValue, bool CallFunc_IsValid_ReturnValue_1);
	void GetArmoryPreview(class ABP_MergedPreviewActor_Loadout_C** Preview, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, TArray<class ABP_MergedPreviewActor_Loadout_C*>& CallFunc_GetAllActorsOfClassWithTag_OutActors, int32 CallFunc_Array_Length_ReturnValue, class ABP_MergedPreviewActor_Loadout_C* CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue);
	class UUI_Shared_CustomizationOption_C* GetOptionWidget(int32 Index, class UUI_Shared_CustomizationOption_C* LocalWidget, class UUI_Shared_CustomizationOption_C* CallFunc_Create_ReturnValue, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, int32 CallFunc_Array_Add_ReturnValue, const struct SlateCore_Margin& K2Node_MakeStruct_Margin, class UUI_Shared_CustomizationOption_C* CallFunc_Array_Get_Item, bool CallFunc_Array_IsValidIndex_ReturnValue, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_1, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_2, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_3, class UVerticalBoxSlot* CallFunc_AddChildToVerticalBox_ReturnValue);
	void GetSelectedItem(bool* Value, struct Valhalla_InventoryItem* InventoryItem, int32 LocalSlotId, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_GetSlotIdByEquipSlot_SlotId, bool CallFunc_GetSlotIdByEquipSlot_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, TArray<struct Valhalla_InventorySlot>& CallFunc_GetCosmeticSlots_CosmeticSlots, class AValInventoryManager* CallFunc_GetInventoryManager_InventoryManager, const struct Valhalla_InventorySlot& CallFunc_Array_Get_Item, bool CallFunc_IsValid_ReturnValue, bool CallFunc_EqualEqual_IntInt_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue);
	void IsSelectingItem(bool* Value, bool CallFunc_MatchesTag_ReturnValue, bool CallFunc_BooleanAND_ReturnValue);
	void BindInventoryManager(class AValInventoryManager* InventoryManager, bool CallFunc_IsValid_ReturnValue, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, TArray<struct Valhalla_InventorySlot>& CallFunc_GetEquippedSlots_EquippedSlots, TArray<struct Valhalla_InventorySlot>& CallFunc_GetCosmeticSlots_CosmeticSlots, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_1);
	void BindSelectors(const struct GameplayTags_GameplayTag& LocalEquipSlot, bool LocalWeapon, class UUI_Shared_CustomizationSelector_C* LocalWidget, bool Temp_bool_Variable, class UUI_Shared_CustomizationSelector_C* CallFunc_Create_ReturnValue, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, const struct SlateCore_Margin& K2Node_MakeStruct_Margin, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, TArray<struct GameplayTags_GameplayTag>& CallFunc_GetEquipSlots_EquipSlots, const struct GameplayTags_GameplayTag& CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_GetEquipSlotId_SlotId, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_1, bool CallFunc_MatchesTag_ReturnValue, class UVerticalBox* K2Node_Select_Default, class UVerticalBoxSlot* CallFunc_AddChildToVerticalBox_ReturnValue);
	void BindPlayer(FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, class AValInventoryManager* CallFunc_GetInventoryManager_ReturnValue, class AValPlayerController* CallFunc_GetPlayer_ReturnValue, bool CallFunc_IsValid_ReturnValue, bool CallFunc_IsValid_ReturnValue_1);
	void OnCosmeticSlotsUpdated(TArray<struct Valhalla_InventorySlot>& Slots, int32 CallFunc_Array_Length_ReturnValue, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, const struct Valhalla_InventorySlot& CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, class UUI_Shared_CustomizationSelector_C* CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue);
	void OnEquipSlotsUpdated(TArray<struct Valhalla_InventorySlot>& Slots, const struct GameplayTags_GameplayTag& LocalEquipSlot, int32 Temp_int_Array_Index_Variable, int32 CallFunc_Array_Length_ReturnValue, const struct Valhalla_InventorySlot& CallFunc_Array_Get_Item, int32 Temp_int_Loop_Counter_Variable, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, class AValInventoryManager* CallFunc_GetInventoryManager_ReturnValue, class UValItemAsset* CallFunc_GetItemAssetById_ItemAsset, bool CallFunc_GetItemAssetById_ReturnValue, bool CallFunc_MatchesAnyTags_ReturnValue, class AValInventoryManager* CallFunc_GetInventoryManager_InventoryManager, const struct GameplayTags_GameplayTag& CallFunc_GetEquipSlotBySlotId_EquipSlot, bool CallFunc_GetEquipSlotBySlotId_ReturnValue);
	void OnOptionUnhovered();
	void OnOptionHovered(const struct GameplayTags_GameplayTag& EquipSlot, const struct Valhalla_InventoryItem& InventoryItem);
	void BindFilters(const TArray<class UWidget*>& LocalWidgets, class UUI_Button_Menu_C* LocalWidget, int32 LocalIndex, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, class UWidget* CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, class UUI_Button_Menu_C* K2Node_DynamicCast_AsUI_Button_Menu, bool K2Node_DynamicCast_bSuccess, bool CallFunc_Less_IntInt_ReturnValue, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, TArray<class UWidget*>& CallFunc_GetAllChildren_ReturnValue);
	void GetEquipSlotId(const struct GameplayTags_GameplayTag& EquipSlot, int32* SlotId, bool CallFunc_IsValid_ReturnValue, int32 CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue);
	void OnOptionSelected(class UUI_Shared_CustomizationOption_C* OptionWidget, bool CallFunc_IsValid_ReturnValue, bool CallFunc_CompareItems_ItemsDiffer, bool CallFunc_IsSelectingJetpack_Value, class AValInventoryManager* CallFunc_GetInventoryManager_ReturnValue, bool CallFunc_IsSelectingJetpack_Value_1, bool CallFunc_IsSelectingItem_Value);
	void OnFilterSelected(int32 Value, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_HasChild_ReturnValue, bool CallFunc_EqualEqual_IntInt_ReturnValue, int32 Temp_int_Loop_Counter_Variable_1, int32 CallFunc_Add_IntInt_ReturnValue_1, TArray<class UUI_Shared_CustomizationSelector_C*>& CallFunc_Map_Values_Values, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_EqualEqual_IntInt_ReturnValue_1, class UUI_Button_Menu_C* CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue, bool Temp_bool_True_if_break_was_hit_Variable, bool CallFunc_Not_PreBool_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, int32 Temp_int_Array_Index_Variable_1, class UUI_Shared_CustomizationSelector_C* CallFunc_Array_Get_Item, TArray<struct GameplayTags_GameplayTag>& CallFunc_Map_Values_Values_1, bool CallFunc_IsVisible_ReturnValue, class UUI_Button_Menu_C* CallFunc_Map_Find_Value_1, bool CallFunc_Map_Find_ReturnValue_1, TArray<struct GameplayTags_GameplayTag>& CallFunc_Map_Keys_Keys, const struct GameplayTags_GameplayTag& CallFunc_Array_Get_Item_1, int32 CallFunc_Array_Length_ReturnValue_1, int32 CallFunc_Array_Find_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue_1, bool CallFunc_GreaterEqual_IntInt_ReturnValue, bool CallFunc_BooleanOR_ReturnValue, class UUI_Shared_CustomizationSelector_C* CallFunc_Map_Find_Value_2, bool CallFunc_Map_Find_ReturnValue_2);
	void OnSlotSelected(const struct GameplayTags_GameplayTag& EquipSlot, class UUI_Shared_CustomizationSelector_C* Widget, class AValInventoryManager* CallFunc_GetInventoryManager_ReturnValue, const struct Valhalla_InventoryItem& CallFunc_GetEquippedCosmeticItemsAt_InventoryItem, bool CallFunc_GetEquippedCosmeticItemsAt_ReturnValue);
	void OnViewShown(TArray<class URHWidget*>& CallFunc_GetSlotNavigationWidgets_NewParam, class URHWidget* CallFunc_Array_Get_Item, class UWidget* CallFunc_SetFocusToThis_ReturnValue, class FName CallFunc_GetCameraTag_CameraTag, const struct Valhalla_InventoryItem& CallFunc_GetDefaultSkin_Item, bool CallFunc_GetDefaultSkin_Valid);
	void GetDefaultSkin(struct Valhalla_InventoryItem* Item, bool* Valid, class AValInventoryManager* CallFunc_GetInventoryManager_InventoryManager, const struct GameplayTags_GameplayTag& CallFunc_MakeLiteralGameplayTag_ReturnValue, bool CallFunc_IsValid_ReturnValue, int32 CallFunc_GetSlotIdByEquipSlot_SlotId, bool CallFunc_GetSlotIdByEquipSlot_ReturnValue, const struct Valhalla_InventorySlot& CallFunc_GetEquippedSlotAt_EquippedSlot, bool CallFunc_GetEquippedSlotAt_ReturnValue);
	void ClearSelectors();
	void GetEquipSlots(TArray<struct GameplayTags_GameplayTag>* EquipSlots, bool CallFunc_IsValid_ReturnValue, TArray<struct GameplayTags_GameplayTag>& CallFunc_Map_Keys_Keys);
	void UpdateIsSelectingViewState(bool Value, bool BypassAnim, int32 CallFunc_SelectInt_ReturnValue, bool Temp_bool_Variable, class FName CallFunc_GetCameraTag_CameraTag, bool CallFunc_Not_PreBool_ReturnValue, class UWidget* K2Node_Select_Default, float CallFunc_GetAnimationCurrentTime_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue_1, class UUMGSequencePlayer* CallFunc_PlayAnimation_ReturnValue, bool CallFunc_SetBool_ReturnValue, bool CallFunc_BooleanAND_ReturnValue);
	void UpdateOptionsHeader(bool Temp_bool_Variable, class FText Temp_text_Variable, class UValGameInstance* CallFunc_GetGameInstance_ReturnValue, class UValDataTableManager* CallFunc_GetDataTableManager_ReturnValue, class FText CallFunc_GetGameplayText_Text, bool CallFunc_GetGameplayText_ReturnValue, class FText K2Node_Select_Default, class FText CallFunc_TextToUpper_ReturnValue);
	void UpdateArmoryItem(const struct Valhalla_InventoryItem& InventoryItem, class UValPreviewManager* CallFunc_GetPreviewManager_PreviewManager, bool CallFunc_GetPreviewManager_Valid);
	void UpdateArmorySkin(const struct Valhalla_InventoryItem& SkinItem, class UValPreviewManager* CallFunc_GetPreviewManager_PreviewManager, bool CallFunc_GetPreviewManager_Valid);
	void UpdateViewModel(bool CallFunc_IsSelectingJetpack_Value, double CallFunc_SelectFloat_ReturnValue, bool CallFunc_GetSelectedItem_Value, const struct Valhalla_InventoryItem& CallFunc_GetSelectedItem_InventoryItem, bool CallFunc_SetBool_ReturnValue, bool CallFunc_IsSelectingItem_Value, const struct Valhalla_InventoryItem& CallFunc_GetDefaultSkin_Item, bool CallFunc_GetDefaultSkin_Valid);
	void UpdateOptions(bool LocalFoundEquipped, int32 LocalItemCount, const struct Valhalla_InventoryItem& LocalItem, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable_1, class UUI_Shared_CustomizationOption_C* CallFunc_GetOptionWidget_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_1, bool CallFunc_IsEquipped_Value, bool CallFunc_IsValid_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, int32 Temp_int_Array_Index_Variable_1, bool CallFunc_Less_IntInt_ReturnValue, class UUI_Shared_CustomizationOption_C* CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue_1, class AValInventoryManager* CallFunc_GetInventoryManager_ReturnValue, TArray<struct Valhalla_InventoryItem>& CallFunc_GetCosmeticItemsForEquipSlot_InventoryItems, int32 CallFunc_Array_Length_ReturnValue_1, const struct Valhalla_InventoryItem& CallFunc_Array_Get_Item_1, int32 CallFunc_Array_Length_ReturnValue_2, bool CallFunc_Less_IntInt_ReturnValue_2);
	void UpdateCamera(class FName Tag, float BlendTime, bool bShouldUpdate, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_IsValid_ReturnValue, TArray<class ACameraActor*>& CallFunc_GetAllActorsOfClassWithTag_OutActors, class ACameraActor* CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_NotEqual_NameName_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, class APlayerController* CallFunc_GetPlayerController_ReturnValue);
	void BndEvt__UI_Lobby_CosmeticCustomization_BackButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
	void InitializeWidgetNavigation();
	void OnHudInitComplete();
	void ExecuteUbergraph_UI_Lobby_CosmeticCustomization(int32 EntryPoint, class APlayerController* CallFunc_GetOwningPlayer_ReturnValue, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, enum class ERH_INPUT_STATE CallFunc_GetCurrentInputState_ReturnValue);
	void OnSelectingViewState__DelegateSignature(bool Selecting);
};

}


