#pragma once




namespace SDK
{
//---------------------------------------------------------------------------------------------------------------------
// CLASSES
//---------------------------------------------------------------------------------------------------------------------

// 0x0 (0x28 - 0x28)
// BlueprintGeneratedClass UIFunctionLibrary.UIFunctionLibrary_C
class UUIFunctionLibrary_C : public UBlueprintFunctionLibrary
{
public:

	static class UClass* StaticClass();
	static class UUIFunctionLibrary_C* GetDefaultObj();

	void GetTimerTextFromSeconds(double Time, int32 MinimumMinutesDigits, class UObject* __WorldContext, class FText* Text, int32 LocalSeconds, int32 LocalMinutes, int32 CallFunc_FTrunc_ReturnValue, int32 CallFunc_Multiply_IntInt_ReturnValue, int32 CallFunc_Divide_IntInt_ReturnValue, double CallFunc_Conv_IntToDouble_ReturnValue, int32 CallFunc_Max_ReturnValue, double CallFunc_Subtract_DoubleDouble_ReturnValue, int32 CallFunc_FTrunc_ReturnValue_1, int32 CallFunc_Max_ReturnValue_1, class FText CallFunc_Conv_IntToText_ReturnValue, const struct Engine_FormatArgumentData& K2Node_MakeStruct_FormatArgumentData, class FText CallFunc_Conv_IntToText_ReturnValue_1, const struct Engine_FormatArgumentData& K2Node_MakeStruct_FormatArgumentData_1, TArray<struct Engine_FormatArgumentData>& K2Node_MakeArray_Array, class FText CallFunc_Format_ReturnValue);
	void GetCreditsId(class UObject* __WorldContext, int32* ItemId, class UValExperienceTrackAsset* LocalRepTrack, int32 LocalAccountRankId);
	void GetAccountRankId(class UObject* __WorldContext, int32* ItemId, class UValExperienceTrackAsset* LocalRepTrack, int32 LocalAccountRankId);
	void GetPlatformIconByDisplayType(enum class ERHPlatformDisplayType Platform, class UObject* __WorldContext, class UTexture2D** Icon, bool K2Node_SwitchEnum_CmpSuccess);
	void GetInventoryItemCount(class URH_PlayerInventory* PlayerInventory, int32 ItemId, class UObject* __WorldContext, int32* ItemCount, int32 LocalItemCount, TArray<struct RallyHereIntegration_RH_ItemInventory>& CallFunc_GetCachedInventoryForItem_ReturnValue, bool CallFunc_IsValid_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, int32 Temp_int_Array_Index_Variable, const struct CoreUObject_DateTime& CallFunc_UtcNow_ReturnValue, const struct RallyHereIntegration_RH_ItemInventory& CallFunc_Array_Get_Item, const struct CoreUObject_DateTime& CallFunc_GetInventoryExpiration_DateTimeOut, bool CallFunc_GetInventoryExpiration_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_GreaterEqual_DateTimeDateTime_ReturnValue, bool CallFunc_BooleanOR_ReturnValue, int32 Temp_int_Loop_Counter_Variable, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_1);
	class FString GetCurrentlySelectedQueueId(class UObject* __WorldContext, class ARHLobbyHUD* LocalHud, class URHQueueDataFactory* CallFunc_GetQueueDataFactory_ReturnValue, class URHPartyManager* CallFunc_GetPartyManager_ReturnValue, bool CallFunc_IsValid_ReturnValue, const class FString& CallFunc_GetSelectedQueueId_ReturnValue, bool CallFunc_IsInParty_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, const class FString& CallFunc_GetSelectedQueueId_ReturnValue_1, class ARHHUDCommon* CallFunc_GetHUDCommon_HUD_Common, class ARHLobbyHUD* K2Node_DynamicCast_AsRHLobby_HUD, bool K2Node_DynamicCast_bSuccess, bool CallFunc_IsValid_ReturnValue_2);
	void GetAccountXPId(class UObject* __WorldContext, int32* ItemId, class UValExperienceTrackAsset* LocalXpTrack, int32 LocalAccountXPId);
	int32 GetLocalPlayerLevel(class UObject* __WorldContext, int32 AccountXPId, int32 CallFunc_GetAccountXPId_ItemId, int32 CallFunc_Get_Local_Count_for_Item_Id_Count, int32 CallFunc_GetXPLevelByCount_ReturnValue);
	void Get_Local_Count_for_Item_Id(int32 ItemId, class UObject* __WorldContext, int32* Count, class ARHHUDCommon* LocalHud, int32 LocalCount, class URHS_PlayerInventory* CallFunc_GetLocalPlayerInventory_ReturnValue, class ARHHUDCommon* CallFunc_GetHUDCommon_HUD_Common, bool CallFunc_IsValid_ReturnValue, int32 CallFunc_GetInventoryItemCount_ItemCount);
	int32 GetXPLevelByCount(int32 Count, class UObject* __WorldContext, bool CallFunc_IsValid_ReturnValue, bool CallFunc_IsValid_ReturnValue_1);
	void GetPartyHighestCountForItemId(int32 ItemId, class UObject* __WorldContext, int32* HighestCount, class ARHHUDCommon* LocalHud, int32 LocalHighestCount, int32 Temp_int_Array_Index_Variable, class URHS_PlayerInventory* CallFunc_GetLocalPlayerInventory_ReturnValue, int32 Temp_int_Loop_Counter_Variable, class URHPartyManager* CallFunc_GetPartyManager_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, TArray<struct RallyHereStart_RH_PartyMemberData>& CallFunc_GetPartyMembers_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, class ARHHUDCommon* CallFunc_GetHUDCommon_HUD_Common, int32 CallFunc_GetInventoryItemCount_ItemCount, bool CallFunc_Greater_IntInt_ReturnValue, bool CallFunc_Greater_IntInt_ReturnValue_1, bool CallFunc_IsValid_ReturnValue);
	void GetQueueTeamSizeDetails(int32 MaxSize, class UObject* __WorldContext, class FText* TeamSizeText, TSoftObjectPtr<class UTexture2D>* TeamSizeIcon, bool K2Node_SwitchInteger_CmpSuccess);
	void Get_Security_Level_Name(uint8 SecurityLevel, class UObject* __WorldContext, class FText* Text, class FText LocalText, bool K2Node_SwitchEnum_CmpSuccess, class FText CallFunc_TextToUpper_ReturnValue);
	void GetMasteryInfoFromPlayerProperty(uint8 InPlayerProperty, int32 TierIndex, class UObject* __WorldContext, TSoftObjectPtr<class UTexture2D>* Icon, class FText* Text, class FText OutText, TSoftObjectPtr<class UTexture2D> OutTexture, bool K2Node_SwitchInteger_CmpSuccess, bool K2Node_SwitchEnum_CmpSuccess, bool K2Node_SwitchEnum_CmpSuccess_1, bool K2Node_SwitchEnum_CmpSuccess_2);
	void GetIconFromPlayerProperty(uint8 InPlayerProperty, class UObject* __WorldContext, class UTexture2D** OutText, uint8 Temp_byte_Variable, class UTexture2D* Temp_object_Variable, class UTexture2D* Temp_object_Variable_1, class UTexture2D* Temp_object_Variable_2, class UTexture2D* Temp_object_Variable_3, class UTexture2D* Temp_object_Variable_4, class UTexture2D* Temp_object_Variable_5, class UTexture2D* Temp_object_Variable_6, class UTexture2D* Temp_object_Variable_7, class UTexture2D* Temp_object_Variable_8, class UTexture2D* Temp_object_Variable_9, class UTexture2D* Temp_object_Variable_10, class UTexture2D* Temp_object_Variable_11, class UTexture2D* Temp_object_Variable_12, class UTexture2D* K2Node_Select_Default);
	void GetTextFromPlayerProperty(uint8 InProperty, class UObject* __WorldContext, class FText* OutText, uint8 Temp_byte_Variable, class FText Temp_text_Variable, class FText Temp_text_Variable_1, class FText Temp_text_Variable_2, class FText Temp_text_Variable_3, class FText Temp_text_Variable_4, class FText Temp_text_Variable_5, class FText Temp_text_Variable_6, class FText Temp_text_Variable_7, class FText Temp_text_Variable_8, class FText Temp_text_Variable_9, class FText Temp_text_Variable_10, class FText Temp_text_Variable_11, class FText Temp_text_Variable_12, class FText K2Node_Select_Default);
	void Get_Formatted_Rarity_Text(uint8 Rarity, class FText Text, class UObject* __WorldContext, class FText* RarityText, class FText LocalRarityText, const struct Engine_FormatArgumentData& K2Node_MakeStruct_FormatArgumentData, TArray<struct Engine_FormatArgumentData>& K2Node_MakeArray_Array, class FText CallFunc_Format_ReturnValue, bool K2Node_SwitchEnum_CmpSuccess);
	void Get_Queue_Image_by_Client_Config(class UObject* __WorldContext, TSoftObjectPtr<class UTexture2D>* QueueDesc, bool Temp_bool_Variable, TSoftObjectPtr<class UTexture2D> Temp_softobject_Variable, TSoftObjectPtr<class UTexture2D> Temp_softobject_Variable_1, TSoftObjectPtr<class UTexture2D> K2Node_Select_Default);
	void GetQueueDescriptionByClientConfig(class UObject* __WorldContext, class FText* QueueDesc, bool Temp_bool_Variable, class FText Temp_text_Variable, class FText CallFunc_GetEmptyText_ReturnValue, class FText K2Node_Select_Default);
	void GetQueueNameByClientConfig(class UObject* __WorldContext, class FText* QueueName, bool CallFunc_Not_PreBool_ReturnValue, bool CallFunc_IsValid_ReturnValue);
	void SaveLocalAction(class FName ActionName, class UObject* __WorldContext, class UGameUserSettings* CallFunc_GetGameUserSettings_ReturnValue, class URHGameUserSettings* K2Node_DynamicCast_AsRHGame_User_Settings, bool K2Node_DynamicCast_bSuccess);
	void IsLocalActionSaved(class FName ActionName, class UObject* __WorldContext, bool* ActionSaved, class UGameUserSettings* CallFunc_GetGameUserSettings_ReturnValue, class URHGameUserSettings* K2Node_DynamicCast_AsRHGame_User_Settings, bool K2Node_DynamicCast_bSuccess, bool CallFunc_IsLocalActionSaved_ReturnValue);
	void GetSettingsDataFactory(class UObject* __WorldContext, class URHSettingsDataFactory** SettingsDataFactory, class ARHHUDCommon* CallFunc_GetHUDCommon_HUD_Common, class URHSettingsDataFactory* CallFunc_GetSettingsDataFactory_ReturnValue);
	void GetHUDCommon(class UObject* __WorldContext, class ARHHUDCommon** HUD_Common, class APlayerController* CallFunc_GetLocalPlayerController_ReturnValue, class AHUD* CallFunc_GetHUD_ReturnValue, class ARHHUDCommon* K2Node_DynamicCast_AsRHHUDCommon, bool K2Node_DynamicCast_bSuccess);
	void AssignActionIcon(class UImage* Image, class FName ActionName, bool MatchSize, class UObject* __WorldContext, const struct InputCore_Key& CallFunc_GetGamepadButtonForAction_Button, bool CallFunc_GetGamepadButtonForAction_ReturnValue, class UTexture2D* CallFunc_GetIconForGamepadButton_Icon);
	void GetInputTypeIcon(enum class ERH_INPUT_STATE InputType, class UObject* __WorldContext, class UTexture2D** Texture, uint8 Temp_byte_Variable, class UTexture2D* Temp_object_Variable, class UTexture2D* Temp_object_Variable_1, class UTexture2D* Temp_object_Variable_2, class UTexture2D* Temp_object_Variable_3, class UTexture2D* K2Node_Select_Default);
	void GetPlatformIcon(enum class ERHAPI_Platform Platform, class UObject* __WorldContext, class UTexture2D** Icon, bool K2Node_SwitchEnum_CmpSuccess);
	void GetFontByName(class FName FontName, class UObject* __WorldContext, bool* HasFound, struct SlateCore_SlateFontInfo* FontInfo, const struct SlateCore_SlateFontInfo& K2Node_MakeStruct_SlateFontInfo, const struct RallyHereStart_FontPaletteInfo& CallFunc_GetDataTableRowFromName_OutRow, bool CallFunc_GetDataTableRowFromName_ReturnValue);
	void GetColorByName(class FName ColorName, class UObject* __WorldContext, bool* HasFound, struct CoreUObject_LinearColor* Color, const struct RallyHereStart_ColorPaletteInfo& CallFunc_GetDataTableRowFromName_OutRow, bool CallFunc_GetDataTableRowFromName_ReturnValue);
	void GetItemType(class UPlatformInventoryItem* InventoryItem, class UObject* __WorldContext, class FText* ItemType, const struct GameplayTags_GameplayTagContainer& CallFunc_GetCollectionContainer_ReturnValue, bool CallFunc_HasTag_ReturnValue, bool CallFunc_HasTag_ReturnValue_1, bool CallFunc_HasTag_ReturnValue_2, bool CallFunc_HasTag_ReturnValue_3, bool CallFunc_HasTag_ReturnValue_4, bool CallFunc_HasTag_ReturnValue_5);
	void GetFormattedTimeSpan(struct CoreUObject_Timespan& Timespan, bool Shorthand, class UObject* __WorldContext, class FText* Text, bool Temp_bool_Variable, int32 CallFunc_BreakTimespan_Days, int32 CallFunc_BreakTimespan_Hours, int32 CallFunc_BreakTimespan_Minutes, int32 CallFunc_BreakTimespan_Seconds, int32 CallFunc_BreakTimespan_Milliseconds, int64 CallFunc_Conv_IntToInt64_ReturnValue, bool CallFunc_EqualEqual_IntInt_ReturnValue, const struct Engine_FormatArgumentData& K2Node_MakeStruct_FormatArgumentData, int64 CallFunc_Conv_IntToInt64_ReturnValue_1, TArray<struct Engine_FormatArgumentData>& K2Node_MakeArray_Array, const struct Engine_FormatArgumentData& K2Node_MakeStruct_FormatArgumentData_1, bool CallFunc_EqualEqual_IntInt_ReturnValue_1, TArray<struct Engine_FormatArgumentData>& K2Node_MakeArray_Array_1, bool CallFunc_Greater_IntInt_ReturnValue, int64 CallFunc_Conv_IntToInt64_ReturnValue_2, bool CallFunc_EqualEqual_IntInt_ReturnValue_2, const struct Engine_FormatArgumentData& K2Node_MakeStruct_FormatArgumentData_2, bool CallFunc_Greater_IntInt_ReturnValue_1, TArray<struct Engine_FormatArgumentData>& K2Node_MakeArray_Array_2, bool Temp_bool_Variable_1, class FText CallFunc_MakeLiteralText_ReturnValue, class FText CallFunc_MakeLiteralText_ReturnValue_1, class FText CallFunc_MakeLiteralText_ReturnValue_2, class FText CallFunc_MakeLiteralText_ReturnValue_3, class FText CallFunc_MakeLiteralText_ReturnValue_4, bool Temp_bool_Variable_2, class FText CallFunc_MakeLiteralText_ReturnValue_5, bool Temp_bool_Variable_3, class FText K2Node_Select_Default, class FText CallFunc_MakeLiteralText_ReturnValue_6, bool Temp_bool_Variable_4, bool Temp_bool_Variable_5, class FText CallFunc_MakeLiteralText_ReturnValue_7, class FText K2Node_Select_Default_1, class FText CallFunc_MakeLiteralText_ReturnValue_8, class FText CallFunc_MakeLiteralText_ReturnValue_9, bool Temp_bool_Variable_6, class FText K2Node_Select_Default_2, class FText CallFunc_Format_ReturnValue, bool Temp_bool_Variable_7, class FText K2Node_Select_Default_3, const struct Engine_FormatArgumentData& K2Node_MakeStruct_FormatArgumentData_3, class FText K2Node_Select_Default_4, class FText CallFunc_MakeLiteralText_ReturnValue_10, class FText K2Node_Select_Default_5, class FText K2Node_Select_Default_6, class FText CallFunc_Format_ReturnValue_1, class FText CallFunc_Format_ReturnValue_2, const struct Engine_FormatArgumentData& K2Node_MakeStruct_FormatArgumentData_4, class FText K2Node_Select_Default_7, const struct Engine_FormatArgumentData& K2Node_MakeStruct_FormatArgumentData_5, TArray<struct Engine_FormatArgumentData>& K2Node_MakeArray_Array_3, class FText CallFunc_Format_ReturnValue_3, class FText CallFunc_TextTrimPrecedingAndTrailing_ReturnValue);
	void GetPlatformViewProfileText(class UObject* __WorldContext, class FText* Return_Value, bool CallFunc_IsPlatform_ReturnValue, bool CallFunc_IsPlatform_ReturnValue_1, bool CallFunc_IsPlatform_ReturnValue_2);
	void GetEnemyColor(class UObject* __WorldContext, struct CoreUObject_LinearColor* Return_Value, bool CallFunc_GetColorByName_HasFound, const struct CoreUObject_LinearColor& CallFunc_GetColorByName_Color);
	void GetFriendlyColor(class UObject* __WorldContext, struct CoreUObject_LinearColor* Return_Value, bool CallFunc_GetColorByName_HasFound, const struct CoreUObject_LinearColor& CallFunc_GetColorByName_Color);
	void FormatSecondsToTimerText(double Seconds, int32 Minute_Digits, bool ShowTenths, class UObject* __WorldContext, class FText* Timer_Text, bool Temp_bool_Variable, const struct CoreUObject_Timespan& CallFunc_FromSeconds_ReturnValue, int32 CallFunc_BreakTimespan_Days, int32 CallFunc_BreakTimespan_Hours, int32 CallFunc_BreakTimespan_Minutes, int32 CallFunc_BreakTimespan_Seconds, int32 CallFunc_BreakTimespan_Milliseconds, class FText Temp_text_Variable, int32 CallFunc_Divide_IntInt_ReturnValue, int64 CallFunc_Conv_IntToInt64_ReturnValue, class FText CallFunc_Conv_IntToText_ReturnValue, const struct Engine_FormatArgumentData& K2Node_MakeStruct_FormatArgumentData, const struct Engine_FormatArgumentData& K2Node_MakeStruct_FormatArgumentData_1, class FText CallFunc_Conv_IntToText_ReturnValue_1, class FText Temp_text_Variable_1, const struct Engine_FormatArgumentData& K2Node_MakeStruct_FormatArgumentData_2, TArray<struct Engine_FormatArgumentData>& K2Node_MakeArray_Array, class FText K2Node_Select_Default, class FText CallFunc_Format_ReturnValue, float CallFunc_FromSeconds_Seconds_ImplicitCast);
	void GetIconForGamepadButton(const struct InputCore_Key& Button, class UObject* __WorldContext, class UTexture2D** Icon, const class FString& PlatformName, bool CallFunc_IsPlatformType_ReturnValue, class FName CallFunc_GetKeyName_ReturnValue, const struct ButtonIconAssoc_ButtonIconAssoc& CallFunc_GetDataTableRowFromName_OutRow, bool CallFunc_GetDataTableRowFromName_ReturnValue, const class FString& CallFunc_GetPlatformName_ReturnValue, enum class EGamepadIcons CallFunc_GetGamepadIconSet_ReturnValue, bool K2Node_SwitchEnum_CmpSuccess, bool CallFunc_EqualEqual_StriStri_ReturnValue, bool CallFunc_EqualEqual_StriStri_ReturnValue_1, bool CallFunc_EqualEqual_StriStri_ReturnValue_2, bool CallFunc_EqualEqual_StriStri_ReturnValue_3, bool CallFunc_EqualEqual_StriStri_ReturnValue_4, bool CallFunc_EqualEqual_StriStri_ReturnValue_5, bool CallFunc_BooleanOR_ReturnValue);
	void GetTeamName(int32 TeamNum, bool Abbreviate, class UObject* __WorldContext, class FText* TeamName, bool Temp_bool_Variable, bool K2Node_SwitchInteger_CmpSuccess, class FText Temp_text_Variable, class FText Temp_text_Variable_1, bool Temp_bool_Variable_1, class FText K2Node_Select_Default, class FText Temp_text_Variable_2, class FText Temp_text_Variable_3, class FText K2Node_Select_Default_1);
	void GetTeamColor(int32 TeamNum, int32 OwningPlayerNum, class UObject* __WorldContext, struct CoreUObject_LinearColor* Team_Color, bool* Found_Color, TMap<int32, struct CoreUObject_LinearColor> TeamColorMap, bool Temp_bool_Variable, bool CallFunc_EqualEqual_IntInt_ReturnValue, TMap<int32, struct CoreUObject_LinearColor> K2Node_MakeVariable_MakeVariableOutput, const struct CoreUObject_LinearColor& CallFunc_GetEnemyColor_Return_Value, const struct CoreUObject_LinearColor& CallFunc_GetFriendlyColor_Return_Value, const struct CoreUObject_LinearColor& K2Node_Select_Default);
};

}


