#pragma once




namespace SDK
{
//---------------------------------------------------------------------------------------------------------------------
// CLASSES
//---------------------------------------------------------------------------------------------------------------------

// 0x450 (0x9B8 - 0x568)
// WidgetBlueprintGeneratedClass WBP_HomeQuickPlay_SingleButton.WBP_HomeQuickPlay_SingleButton_C
class UWBP_HomeQuickPlay_SingleButton_C : public URHQuickPlayWidget
{
public:
	struct Engine_PointerToUberGraphFrame        UberGraphFrame;                                    // 0x568(0x8)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                      PlayBtnHover;                                      // 0x570(0x8)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UDropdown_C*                           Dropdown;                                          // 0x578(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCanvasPanel*                          EntryCostGroup;                                    // 0x580(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                            EntryCostText;                                     // 0x588(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                              GamemodeDisplayWrapper;                            // 0x590(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                            GameModeNameTextForJoin;                           // 0x598(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                Image_66;                                          // 0x5A0(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                Image_126;                                         // 0x5A8(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                            ModeTypeLabel;                                     // 0x5B0(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_PartyFillChoice_C*                PartyFillChoice;                                   // 0x5B8(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                PlayBtn_Fill;                                      // 0x5C0(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                PlayBtn_Fill_1;                                    // 0x5C8(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                PlayBtn_Fill_2;                                    // 0x5D0(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                PlayBtn_Fill_3;                                    // 0x5D8(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                PlayBtn_Fill_4;                                    // 0x5E0(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                PlayBtn_Fill_6;                                    // 0x5E8(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                PlayBtn_HoverFill;                                 // 0x5F0(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                PlayBtnGamepadCallout;                             // 0x5F8(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UStandardButtonNoArt_C*                PlayBtnHitTarget;                                  // 0x600(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                PlayBtnStatus_Fill;                                // 0x608(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                PlayBtnStatus_Fill_1;                              // 0x610(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                PlayBtnStatus_HoverFill;                           // 0x618(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                PlayBtnStatus_HoverFill_1;                         // 0x620(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                              PlayButton_CancelMode;                             // 0x628(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                              PlayButton_JoinMode;                               // 0x630(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                              PlayButton_StatusMode;                             // 0x638(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetSwitcher*                       PlayButtonStateSwitcher;                           // 0x640(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_KeyCallout_C*                     Prompt_LeaveQueue;                                 // 0x648(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                        QueuePreferenceButtons;                            // 0x650(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCanvasPanel*                          QueueWarningGroup;                                 // 0x658(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_Button_Menu_C*                     SoloButton;                                        // 0x660(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_Button_Menu_C*                     SquadButton;                                       // 0x668(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                            StatusMsgText;                                     // 0x670(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UScaleBox*                             StatusMsgWrapper;                                  // 0x678(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                            StatusText;                                        // 0x680(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	bool                                         PlayShortcutEnabled;                               // 0x688(0x1)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                        Pad_2A84[0x7];                                     // Fixing Size After Last Property  
	class FText                                  StatusMsg_Unknown;                                 // 0x690(0x18)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FText                                  StatusMsg_NoQueuesAvailable;                       // 0x6A8(0x18)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FText                                  StatusMsg_NoSelection;                             // 0x6C0(0x18)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FText                                  StatusMsg_QueueUnavailable;                        // 0x6D8(0x18)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FText                                  StatusMsg_PartyLimit;                              // 0x6F0(0x18)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FText                                  StatusMsg_ReadyToJoin;                             // 0x708(0x18)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FText                                  StatusMsg_WaitingForLeader;                        // 0x720(0x18)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FText                                  StatusMsg_QueuedStatus;                            // 0x738(0x18)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FText                                  StatusMsg_EnteringMatch;                           // 0x750(0x18)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FText                                  StatusMsg_PartyLevel;                              // 0x768(0x18)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FText                                  StatusMsg_PlayerLevel;                             // 0x780(0x18)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FText                                  Msg_ChooseGamemode;                                // 0x798(0x18)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FText                                  Msg_CancelSearch;                                  // 0x7B0(0x18)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                         bPlayBtnEnabled;                                   // 0x7C8(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                         bSupplementaryBtnEnabled;                          // 0x7C9(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                        Pad_2A93[0x6];                                     // Fixing Size After Last Property  
	FMulticastInlineDelegateProperty_            TriggerStatusModeDisplayUpdate;                    // 0x7D0(0x10)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	bool                                         bForceFirstTimeUpdate;                             // 0x7E0(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                        Pad_2A9A[0x7];                                     // Fixing Size After Last Property  
	double                                       CurrentQueueTimeElapsed;                           // 0x7E8(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                  Msg_ReadyToRejoin;                                 // 0x7F0(0x18)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FText                                  Msg_LeaveMatch;                                    // 0x808(0x18)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FText                                  Msg_LeaveCustomMatch;                              // 0x820(0x18)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance)
	struct Engine_TimerHandle                    PendingQueueUpdateTimer;                           // 0x838(0x8)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	double                                       PendingQueueUpdateTimeoutTime;                     // 0x840(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                         MsgLeaveCustomLobby;                               // 0x848(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                        Pad_2A9E[0x7];                                     // Fixing Size After Last Property  
	class UObject*                               ClickPlayBtnHomeQuickPlaySFX;                      // 0x850(0x8)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	class UObject*                               ClickCancelBtnHomeQuickPlaySFX;                    // 0x858(0x8)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	class FText                                  StatusMsg_PartyLimitMin;                           // 0x860(0x18)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FText                                  StatusMsg_RankedRangeTooFar;                       // 0x878(0x18)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                         LeaveQueueShortcutEnabled;                         // 0x890(0x1)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                        Pad_2AA2[0x7];                                     // Fixing Size After Last Property  
	class FText                                  StatusMsg_PartyPlatformDisallowed;                 // 0x898(0x18)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FText                                  StatusMsg_Retrying;                                // 0x8B0(0x18)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FText                                  StatusMsg_PlayerOwnedJobs;                         // 0x8C8(0x18)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FText                                  StatusMsg_PartyOwnedJobs;                          // 0x8E0(0x18)(Edit, BlueprintVisible, DisableEditOnInstance)
	class URHQueueDataFactory*                   QueueDataFactory;                                  // 0x8F8(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                         Queue_for_Solo;                                    // 0x900(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                        Pad_2AB8[0x7];                                     // Fixing Size After Last Property  
	class UAudioComponent*                       SFXAudioCompBtnLoop;                               // 0x908(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class FString                                PrimaryQueueID;                                    // 0x910(0x10)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	class FString                                SecondaryQueueID;                                  // 0x920(0x10)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	bool                                         CachedDisableQueueToggle;                          // 0x930(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                         bRegisteredNav;                                    // 0x931(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                        Pad_2AC0[0x6];                                     // Fixing Size After Last Property  
	TArray<class FString>                        BlockedSessionIds;                                 // 0x938(0x10)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class URH_SessionView*>               SearchedSessions;                                  // 0x948(0x10)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                         bSuccessfulBackfill;                               // 0x958(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                        Pad_2AC5[0x7];                                     // Fixing Size After Last Property  
	TMap<int32, class FString>                   DevQueueOptionMap;                                 // 0x960(0x50)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                         CachedHideDevSelectMenu;                           // 0x9B0(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                        Pad_2ACB[0x3];                                     // Fixing Size After Last Property  
	int32                                        CachedLastSelectedDevQueueIndex;                   // 0x9B4(0x4)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

	static class UClass* StaticClass();
	static class UWBP_HomeQuickPlay_SingleButton_C* GetDefaultObj();

	void OnDevQueueSelectionChanged(class FText SelectionText, int32 SelectionIndex);
	bool ShouldShowDevSelect(bool CallFunc_Not_PreBool_ReturnValue);
	void UpdateDevSelectMenuVisibility(bool LocalShowDevSelect, double CallFunc_SelectFloat_ReturnValue, const struct CoreUObject_Vector2D& CallFunc_MakeVector2D_ReturnValue, bool CallFunc_ShouldShowDevSelect_ReturnValue);
	void UpdateDevQueueOptions(const class FString& LocalPreferredQueueSelection, int32 PrimaryQueueOption, int32 Index, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable, TArray<class FString>& CallFunc_Map_Values_Values, bool CallFunc_Greater_IntInt_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, int32 Temp_int_Variable, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, const class FString& CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_1, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_1, int32 Temp_int_Loop_Counter_Variable_1, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_2, int32 Temp_int_Array_Index_Variable_1, const class FString& CallFunc_Array_Get_Item, bool CallFunc_SetSelectedOptionByIndex_Success, bool CallFunc_EqualEqual_StrStr_ReturnValue, bool CallFunc_SetSelectedOptionByIndex_Success_1, TArray<class URH_MatchmakingQueueInfo*>& CallFunc_GetQueues_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_1, class URH_MatchmakingQueueInfo* CallFunc_Array_Get_Item_1, bool CallFunc_Less_IntInt_ReturnValue_1, const class FString& CallFunc_GetQueueId_ReturnValue, bool CallFunc_EqualEqual_StrStr_ReturnValue_1, bool CallFunc_IsActive_ReturnValue, bool CallFunc_IsValid_ReturnValue, bool CallFunc_IsValid_ReturnValue_1);
	void UpdateQueueTypeNav(bool Temp_bool_Variable, bool Temp_bool_Variable_1, class UWidget* K2Node_Select_Default, class UWidget* K2Node_Select_Default_1);
	void OnAppSettingsUpdated(class URH_ConfigSubsystem* ConfigSubsystem);
	void OnPlayerInventoryCacheUpdated(TArray<int32>& ItemIds);
	class FString Get_Queue_IDSetting(const class FString& AppSetting, bool* Valid, class URH_GameInstanceSubsystem* CallFunc_GetGameInstanceSubsystem_ReturnValue, class URH_ConfigSubsystem* CallFunc_GetConfigSubsystem_ReturnValue, bool CallFunc_IsValid_ReturnValue, const class FString& CallFunc_GetAppSetting_Value, bool CallFunc_GetAppSetting_ReturnValue);
	void UpdateSettings(class URH_ConfigSubsystem* LocalConfigSubsystem, const class FString& CallFunc_Get_Queue_IDSetting_ReturnValue, bool CallFunc_Get_Queue_IDSetting_Valid, const class FString& CallFunc_GetAppSetting_Value, bool CallFunc_GetAppSetting_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, bool CallFunc_EqualEqual_StriStri_ReturnValue, bool CallFunc_BooleanOR_ReturnValue, const class FString& CallFunc_Get_Queue_IDSetting_ReturnValue_1, bool CallFunc_Get_Queue_IDSetting_Valid_1, const class FString& CallFunc_GetAppSetting_Value_1, bool CallFunc_GetAppSetting_ReturnValue_1, class URH_GameInstanceSubsystem* CallFunc_GetGameInstanceSubsystem_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue_1, class URH_ConfigSubsystem* CallFunc_GetConfigSubsystem_ReturnValue, bool CallFunc_EqualEqual_StriStri_ReturnValue_1, bool CallFunc_BooleanOR_ReturnValue_1);
	void IsPartyFillFeatureEnabled(bool* Enabled, class URH_GameInstanceSubsystem* CallFunc_GetGameInstanceSubsystem_ReturnValue, class URH_ConfigSubsystem* CallFunc_GetConfigSubsystem_ReturnValue, const class FString& CallFunc_GetAppSetting_Value, bool CallFunc_GetAppSetting_ReturnValue, bool CallFunc_IsValid_ReturnValue, bool CallFunc_EqualEqual_StriStri_ReturnValue, bool CallFunc_BooleanAND_ReturnValue);
	void On_Party_Local_Player_Kicked();
	void OnPartyInvitationAccepted();
	void OnQueueChanged();
	void OnPendingPartyMemberAccepted(const struct RallyHereStart_RH_PartyMemberData& PartyMember, bool CallFunc_IsReady_IsReady);
	void OnPartyLocalPlayerPromoted();
	void UpdateMissionCost(class FText Temp_text_Variable, int32 CallFunc_Get_Local_Count_for_Item_Id_Count, bool Temp_bool_Variable, int32 CallFunc_CalculateDisplayEntryCost_ReturnValue, class FText CallFunc_Conv_IntToText_ReturnValue, bool CallFunc_Greater_IntInt_ReturnValue, class FText K2Node_Select_Default);
	void UpdateSoloButtonState(class URHPartyManager* LocalPartyDataFactory);
	void SetDefaultQueuePreference(int32 LocalValue, const class FString& CallFunc_GetSelectedQueueId_ReturnValue, class URH_MatchmakingQueueInfo* CallFunc_GetQueueInfoById_ReturnValue, bool CallFunc_IsValid_ReturnValue, bool CallFunc_EqualEqual_IntInt_ReturnValue);
	void OnQueuePreferenceButtonSelected(int32 Value, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_IsPartyFillFeatureEnabled_Enabled, class UGameUserSettings* CallFunc_GetGameUserSettings_ReturnValue, class UValGameUserSettings* K2Node_DynamicCast_AsVal_Game_User_Settings, bool K2Node_DynamicCast_bSuccess, bool CallFunc_EqualEqual_IntInt_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, TArray<class UWidget*>& CallFunc_GetAllChildren_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, class UWidget* CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, class UUI_Button_Menu_C* K2Node_DynamicCast_AsUI_Button_Menu, bool K2Node_DynamicCast_bSuccess_1, bool CallFunc_EqualEqual_IntInt_ReturnValue_1);
	void BindQueuePreferenceButtons(int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, class UGameUserSettings* CallFunc_GetGameUserSettings_ReturnValue, int32 CallFunc_SelectInt_ReturnValue, class UValGameUserSettings* K2Node_DynamicCast_AsVal_Game_User_Settings, bool K2Node_DynamicCast_bSuccess, bool CallFunc_GetSquadsQueueSelected_ReturnValue, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, bool CallFunc_Not_PreBool_ReturnValue, TArray<class UWidget*>& CallFunc_GetAllChildren_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, class UWidget* CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, class UUI_Button_Menu_C* K2Node_DynamicCast_AsUI_Button_Menu, bool K2Node_DynamicCast_bSuccess_1);
	void GetSoloQueuePreference(bool* QueueForSolo);
	void GetSkillScore(int32* SkillScore, int32 LocalHighestCount, int32 ReputationId, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_Get_Local_Count_for_Item_Id_Count, bool CallFunc_Greater_IntInt_ReturnValue, class URHPartyManager* CallFunc_GetPartyManager_ReturnValue, TArray<struct RallyHereStart_RH_PartyMemberData>& CallFunc_GetPartyMembers_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, const struct RallyHereStart_RH_PartyMemberData& CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, class URH_PlayerInventory* CallFunc_GetPlayerInventory_ReturnValue, bool CallFunc_IsValid_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, int32 CallFunc_GetInventoryItemCount_ItemCount, bool CallFunc_Greater_IntInt_ReturnValue_1);
	void GetBestQueue(class FString* QueueId, class URH_MatchmakingQueueInfo* LocalClientQueueInfo, int32 MaxPartyQueueId, bool DesiresSolo, int32 LocalMaxLevel, const class FString& LocalBestQueueId, int32 LocalMinLevel, int32 LocalHighestMin, int32 LocalCurrentLevel, bool CallFunc_ShouldShowDevSelect_ReturnValue, bool Temp_bool_Variable, class FText CallFunc_GetSelectedOption_Selection, int32 CallFunc_GetSelectedOption_Index, bool CallFunc_Not_PreBool_ReturnValue, const class FString& CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, const class FString& K2Node_Select_Default, bool CallFunc_GetSoloQueuePreference_QueueForSolo, bool CallFunc_IsValid_ReturnValue);
	void Calculate_Matchmaking_Attributes(struct RallyHereStart_RHMatchmakingAttributes* Attributes, TSet<class FString> Local_Matchmaking_Tag_Attributes, TMap<class FString, double> Local_Matchmaking_Double_Attributes, const class FString& Temp_string_Variable, bool CallFunc_IsPartyFillFeatureEnabled_Enabled, bool CallFunc_Not_PreBool_ReturnValue, const struct RallyHereStart_RHMatchmakingAttributes& K2Node_MakeStruct_RHMatchmakingAttributes, const class FString& Temp_string_Variable_1, int32 CallFunc_GetSkillScore_SkillScore, double CallFunc_Conv_IntToDouble_ReturnValue, bool CallFunc_IsChecked_Checked, bool CallFunc_BooleanOR_ReturnValue, TMap<class FString, float> K2Node_MakeStruct_DoubleAttributes_ImplicitCast);
	void On_Party_Updated(bool CallFunc_IsValid_ReturnValue, class URHPartyManager* CallFunc_GetPartyManager_ReturnValue, bool CallFunc_IsInParty_ReturnValue);
	void UpdatePartyMemberReady(bool CallFunc_IsReady_IsReady, enum class EQuickPlayQueueState CallFunc_GetCurrentQuickPlayState_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, bool CallFunc_NotEqual_ByteByte_ReturnValue);
	void OnPartyMemberDataUpdated(const struct RallyHereStart_RH_PartyMemberData& PartyMember);
	void BindPartyReadyEvents(class URHQueueDataFactory* LocalQueueFactory, class URHPartyManager* LocalPartyFactory, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_1, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_2, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_3, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_4, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_5, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_6, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_7, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_8, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_9, class ARHLobbyHUD* K2Node_DynamicCast_AsRHLobby_HUD, bool K2Node_DynamicCast_bSuccess, class URHPartyManager* CallFunc_GetPartyManager_ReturnValue, class URHQueueDataFactory* CallFunc_GetQueueDataFactory_ReturnValue);
	void OnPartyMemberReadyUpdated(class UObject* Sender, bool IsReady);
	void SetIsReady(bool bIsReady, class ARHHUDCommon* CallFunc_GetHUDCommon_HUD_Common, class URHPartyManager* CallFunc_GetPartyManager_ReturnValue, bool CallFunc_IsValid_ReturnValue, bool CallFunc_IsValid_ReturnValue_1);
	void IsReady(bool* IsReady, class ARHHUDCommon* CallFunc_GetHUDCommon_HUD_Common, class URHPartyManager* CallFunc_GetPartyManager_ReturnValue, bool CallFunc_IsValid_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, bool CallFunc_IsReady_ReturnValue);
	void IsPartyReady(bool* PartyIsReady, class ARHHUDCommon* CallFunc_GetHUDCommon_HUD_Common, class URHPartyManager* CallFunc_GetPartyManager_ReturnValue, bool CallFunc_IsValid_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, bool CallFunc_IsPartyReady_ReturnValue);
	void UpdateButtonState(bool bIsReady, bool bPartyIsReady, enum class EQuickPlayQueueState QuickPlayState, bool bCanControl, bool Temp_bool_Variable, class FText Temp_text_Variable, class FText Temp_text_Variable_1, bool Temp_bool_Variable_1, class FText Temp_text_Variable_2, bool Temp_bool_Variable_2, class FText Temp_text_Variable_3, class FText Temp_text_Variable_4, int32 CallFunc_SelectInt_ReturnValue, bool CallFunc_EqualEqual_ByteByte_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, enum class ESlateVisibility Temp_byte_Variable, bool CallFunc_Not_PreBool_ReturnValue_1, bool CallFunc_BooleanAND_ReturnValue, bool CallFunc_IsPartyFillFeatureEnabled_Enabled, bool CallFunc_BooleanAND_ReturnValue_1, bool CallFunc_IsPartyFillFeatureEnabled_Enabled_1, class FText K2Node_Select_Default, bool Temp_bool_Variable_3, enum class ESlateVisibility Temp_byte_Variable_1, bool CallFunc_Not_PreBool_ReturnValue_2, bool CallFunc_NotEqual_ByteByte_ReturnValue, class FText K2Node_Select_Default_1, class FText K2Node_Select_Default_2, bool CallFunc_BooleanAND_ReturnValue_2, bool Temp_bool_Variable_4, bool CallFunc_IsReady_IsReady, bool CallFunc_IsPartyReady_PartyIsReady, enum class EQuickPlayQueueState CallFunc_GetCurrentQuickPlayState_ReturnValue, enum class ESlateVisibility Temp_byte_Variable_2, int32 CallFunc_SelectInt_ReturnValue_1, enum class ESlateVisibility K2Node_Select_Default_3, enum class ESlateVisibility K2Node_Select_Default_4, bool CallFunc_GetQueuePermissions_CanControl, bool CallFunc_GetQueuePermissions_CanQueue);
	void IsTrainingQueue(int32 QueueId, bool* IsTraining, const TArray<int32>& TrainingQueueIds, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, TArray<int32>& K2Node_MakeArray_Array, int32 CallFunc_Array_Length_ReturnValue, int32 CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_EqualEqual_IntInt_ReturnValue);
	class FText GetQueuedTimeText(class FText CallFunc_FormatSecondsToTimerText_Timer_Text, const struct Engine_FormatArgumentData& K2Node_MakeStruct_FormatArgumentData, TArray<struct Engine_FormatArgumentData>& K2Node_MakeArray_Array, class FText CallFunc_Format_ReturnValue);
	void UpdateQueueTimer(bool CallFunc_Greater_DoubleDouble_ReturnValue, bool CallFunc_IsPendingQueueUpdate_ReturnValue, int32 CallFunc_SelectInt_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, class FText CallFunc_FormatSecondsToTimerText_Timer_Text, enum class EQuickPlayQueueState CallFunc_GetCurrentQuickPlayState_ReturnValue, bool CallFunc_EqualEqual_ByteByte_ReturnValue, bool CallFunc_BooleanAND_ReturnValue);
	void HandleQuickPlayStateUpdate(enum class EQuickPlayQueueState LocalQuickPlayState, bool bCanControl, enum class EQuickPlayQueueState CallFunc_GetCurrentQuickPlayState_ReturnValue, bool K2Node_SwitchEnum_CmpSuccess);
	void ApplyKeyShortcutsEnabled(bool Temp_bool_Variable, enum class ESlateVisibility Temp_byte_Variable, enum class ESlateVisibility Temp_byte_Variable_1, enum class ERH_INPUT_STATE CallFunc_GetCurrentInputState_ReturnValue, bool CallFunc_EqualEqual_ByteByte_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, enum class ESlateVisibility K2Node_Select_Default);
	void GetNavigationWidgets(TArray<class URHWidget*>* Return_Value, TArray<class URHWidget*>& K2Node_MakeArray_Array);
	void HandleInputModeChanged(enum class ERH_INPUT_STATE InputMode);
	void SetupGamepadCallout(const struct InputCore_Key& CallFunc_GetGamepadButtonForAction_Button, bool CallFunc_GetGamepadButtonForAction_ReturnValue, class UTexture2D* CallFunc_GetIconForGamepadButton_Icon);
	void BndEvt__PlayBtnHitTarget_K2Node_ComponentBoundEvent_0_OnHovered__DelegateSignature(class UWidget* Widget);
	void BndEvt__PlayBtnHitTarget_K2Node_ComponentBoundEvent_3_OnUnhovered__DelegateSignature(class UWidget* Widget);
	void BndEvt__PlayBtnHitTarget_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature();
	void OnUpdateQuickPlayState(enum class EQuickPlayQueueState QueueState);
	void OnSelectedQueueUpdate(class URH_MatchmakingQueueInfo* CurrentSelectedQueue);
	void InitializeWidgetNavigation();
	void OnQueueStateUpdate(enum class ERH_MatchStatus CurrentMatchStatus);
	void OnUpdateQueueTimeElapsed(float TimeElapsed);
	void Pending_Queue_Update_Timeout();
	void HandleCustomQueueUpdate();
	void ForceClickPlayButton();
	void OnHudBindingReady();
	void OnPartyMemberPromoted(int64 PlayerId);
	void InitializeWidget();
	void ExecuteUbergraph_WBP_HomeQuickPlay_SingleButton(int32 EntryPoint, enum class EQuickPlayQueueState K2Node_Event_QueueState, enum class EQuickPlayQueueState CallFunc_GetCurrentQuickPlayState_ReturnValue, class URH_MatchmakingQueueInfo* K2Node_Event_CurrentSelectedQueue, bool CallFunc_EqualEqual_ByteByte_ReturnValue, bool CallFunc_EqualEqual_ByteByte_ReturnValue_1, enum class EQuickPlayQueueState CallFunc_GetCurrentQuickPlayState_ReturnValue_1, bool CallFunc_GetQueuePermissions_CanControl, bool CallFunc_GetQueuePermissions_CanQueue, bool CallFunc_EqualEqual_ByteByte_ReturnValue_2, bool CallFunc_Not_PreBool_ReturnValue, enum class ERH_MatchStatus K2Node_Event_CurrentMatchStatus, float K2Node_Event_TimeElapsed, bool CallFunc_UIX_AttemptLeaveMatch_ReturnValue, class ARHLobbyHUD* K2Node_DynamicCast_AsRHLobby_HUD, bool K2Node_DynamicCast_bSuccess, class URHQueueDataFactory* CallFunc_GetQueueDataFactory_ReturnValue, bool CallFunc_AddViewRoute_ReturnValue, class ABP_BrightLobbyHUD_C* K2Node_DynamicCast_AsBP_Bright_Lobby_HUD, bool K2Node_DynamicCast_bSuccess_1, class URHQueueDataFactory* CallFunc_GetQueueDataFactory_ReturnValue_1, bool CallFunc_IsInCustomMatch_ReturnValue, float CallFunc_GetAnimationCurrentTime_ReturnValue, class UUMGSequencePlayer* CallFunc_PlayAnimation_ReturnValue, class UUMGSequencePlayer* CallFunc_PlayAnimation_ReturnValue_1, bool CallFunc_UIX_AttemptJoinSelectedQueue_ReturnValue, const class FString& CallFunc_GetBestQueue_QueueId, bool CallFunc_IsValid_ReturnValue, bool CallFunc_SetSelectedQueueId_ReturnValue, const struct RallyHereStart_RHMatchmakingAttributes& CallFunc_Calculate_Matchmaking_Attributes_Attributes, class UWidget* K2Node_ComponentBoundEvent_Widget, bool CallFunc_SetSelectedMatchmakingAttributes_ReturnValue, class UWidget* K2Node_ComponentBoundEvent_Widget_1, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, int64 K2Node_CustomEvent_PlayerId, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_1, class URH_PlayerInfo* CallFunc_GetLocalPlayerInfo_ReturnValue, bool CallFunc_UIX_AttemptCancelQueue_ReturnValue, class URH_PlayerInventory* CallFunc_GetPlayerInventory_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, bool CallFunc_IsValid_ReturnValue_2, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_2, class URH_GameInstanceSubsystem* CallFunc_GetGameInstanceSubsystem_ReturnValue, class URH_ConfigSubsystem* CallFunc_GetConfigSubsystem_ReturnValue, bool CallFunc_IsValid_ReturnValue_3, bool CallFunc_GetSoloQueuePreference_QueueForSolo, double K2Node_VariableSet_CurrentQueueTimeElapsed_ImplicitCast);
	void TriggerStatusModeDisplayUpdate__DelegateSignature();
};

}


